# Generated by Django 3.2 on 2021-04-17 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignbed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='mobile',
        ),
    ]
